# Generated by Django 6.0.6 on 2026-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='É WhatsApp?')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('segmento', models.CharField(max_length=100, verbose_name='Segmento')),
                ('faturamento', models.CharField(max_length=100, verbose_name='Faturamento Aproximado')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lgpd_consentimento', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
